title: Jim Lavrenz
email: 
description: Software Engineer / Embedded AI/ML

github_username:  jimlavrenz
linkedin_username: jimlavrenz

theme: minima

# markdown: GFM

collections:
  notes:
    output: true
