title: Jim Lavrenz
email: 
description: Software Engineer | Embedded | ML/AI

github_username:  jimlavrenz
linkedin_username: jimlavrenz

theme: minima

# markdown: GFM

collections:
  notes:
    output: true
